mytodo: main.o addtask.o deletetask.o listtask.o countitem.o getid.o printlist.o 
	gcc -o mytodo main.o addtask.o deletetask.o listtask.o countitem.o getid.o printlist.o
main.o: main.c myheader.h
	gcc -c main.c
addtask.o: addtask.c myheader.h
	gcc -c addtask.c
deletetask.o: deletetask.c myheader.h
	gcc -c deletetask.c
listtask.o: listtask.c myheader.h
	gcc -c listtask.c
countitem.o: countitem.c myheader.h
	gcc -c countitem.c
getid.o: getid.c myheader.h
	gcc -c getid.c
printlist.o: printlist.c myheader.h
	gcc -c printlist.c
